# Begin /etc/httpd/vhosts.d/wiki.br.linuxfromscratch.org.conf

<VirtualHost *:80>
    ServerName  wiki.br.linuxfromscratch.org

    ServerAdmin webmaster@www.br.linuxfromscratch.org
    DocumentRoot /srv/www/www.br.linuxfromscratch.org/wiki
    CustomLog /var/log/httpd/wiki.br.linuxfromscratch.org-access.log \
       "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
    SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown

    RewriteEngine on
    RewriteCond %{SERVER_NAME} =wiki.br.linuxfromscratch.org
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

# End /etc/httpd/vhosts.d/wiki.br.linuxfromscratch.org.conf
