[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name "Arquivos do sítio LFS brasileiro"

[options] --package-version 1.0

[options] --keep 0

[options] --width 72

[options] --wrap-po 72

[options] --master-charset UTF-8

[po4a_langs] pt_BR

[po4a_paths] xhtml/po/lfs/errata/13.0-systemd/$master.pot pt_BR:xhtml/po/lfs/errata/13.0-systemd/$master.$lang.po
[type: xhtml] xhtml/upstream/lfs/errata/13.0-systemd/index.html pt_BR:xhtml/translated/lfs/errata/13.0-systemd/index.html



#[po4a_paths] xhtml/po/blfs/$master.pot pt_BR:xhtml/po/blfs/$master.$lang.po
#[po4a_paths] xhtml/po/hints/$master.pot pt_BR:xhtml/po/hints/$master.$lang.po

#[type: xhtml] xhtml/upstream/lfs/news.html pt_BR:xhtml/translated/lfs/news.html
#[type: xhtml] xhtml/upstream/lfs/read.html pt_BR:xhtml/translated/lfs/read.html

#[type: xhtml] xhtml/upstream/blfs/news.html pt_BR:xhtml/translated/blfs/news.html
#[type: xhtml] xhtml/upstream/blfs/typosetting.html pt_BR:xhtml/translated/blfs/typosetting.html
#[type: xhtml] xhtml/upstream/hints/howtowrite.html pt_BR:xhtml/translated/hints/howtowrite.html
#[type: xhtml] xhtml/upstream/hints/read.html pt_BR:xhtml/translated/hints/read.html
