[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name "Arquivos do sítio LFS brasileiro"

[options] --package-version 1.0

[options] --keep 0

[options] --width 72

[options] --wrap-po 72

[po4a_langs] pt_BR

[po4a_paths] po/$master.pot pt_BR:po/$master.$lang.po

[type: xhtml] index.html pt_BR:../../slfs/index.html

[type: xhtml] header.html pt_BR:../../slfs/header.html
